#!/bin/bash
source etc/banner
source etc/PIPELINE






function filedatfinder {
cd $dmp
prompt="Please select a file to find tipe encrypt:"
options=( $(find *.dat) )

PS3="$prompt "
select dat in "${options[@]}" "Quit" ; do 
    if (( REPLY == 1 + ${#options[@]} )) ; then
        break

    elif (( REPLY > 0 && REPLY <= ${#options[@]} )) ; then
        echo  "You picked $dat which is file $REPLY"
         break
    else
        echo "Invalid option. Try another one."
    fi
done
cd $tx
}



function dirdatfolder {
cd $fdr
file2="$dat"
if [[ -f "$file2" ]]
  then
     #file detect
     rm $fdr/"$dat" >/dev/null
     echo ""> $fdr/"$dat"
     #folder detect
     rm  -rf $down/output/"$dat" >/dev/null
     mkdir $down/output/"$dat"  
  else
    echo ""> $fdr/"$dat"
    mkdir $down/output/"$dat"
fi
cd $tx
}





function pilkeystr {
    read -p "Please input decimpressed file: " keyr
    echo "are you sure the key is $keyr"
    read -p "Y OR N : " pil
       if [ $pil == Y ];
          then
              echo " OK THEN"
       elif [ $pil == y ];
          then 
              echo " OK THEN"
       else
            exit
     fi
}



function i90 {
cd $tx
for i in {1..1000}
do
qemu-i386 $PREFIX/share/quickbms/quickbms -a "$1" etc/toolcom.bms /storage/emulated/0/Download/dmp/$dat /storage/emulated/0/Download/output/$dat

done
}

function i90k {
cd $tx
for i in {1..1000}
do
qemu-i386 $PREFIX/share/quickbms/quickbms -a "$1 $keyr" etc/toolcom.bms /storage/emulated/0/Download/dmp/$dat /storage/emulated/0/Download/output/$dat

done
}





#HEAD PROGRAM
echo "option 1 adalah option untuk tidak menggunakan decompressed offset"
echo "option 1 adalah option untuk menggunakan decompressed offset"

PS3='Please enter your choice: '
options=("option 1" "option 2" "Quit")
select dadi in "${options[@]}"
do
    case $dadi in
        "option 1")
            filedatfinder
            dirdatfolder
            i90
            ;;
        "Quit")
            exit
            
            ;;
        "option 2")
            filedatfinder
            dirdatfolder
            pilkeystr
            i90k
            ;;
        *) echo "invalid option $REPLY";;
    esac
done 


