#!/bin/bash
source etc/banner
source etc/PIPELINE






function filedatfinder {
cd $dmp
prompt="Please select a file to find tipe encrypt:"
options=( $(find *.dat) )

PS3="$prompt "
select dat in "${options[@]}" "Quit" ; do 
    if (( REPLY == 1 + ${#options[@]} )) ; then
        break

    elif (( REPLY > 0 && REPLY <= ${#options[@]} )) ; then
        echo  "You picked $dat which is file $REPLY"
         break
    else
        echo "Invalid option. Try another one."
    fi
done
}



function dirdatfolder {
cd $fdr
file2="$dat"
if [[ -f "$file2" ]]
  then
     #file detect
     rm $fdr/"$dat" >/dev/null
     echo ""> $fdr/"$dat"
     #folder detect
     rm  -rf $down/output/"$dat" >/dev/null
     mkdir $down/output/"$dat"  
  else
    echo ""> $fdr/"$dat"
    mkdir $down/output/"$dat"
fi
}









function i90 {

for i in {1..90}
  do
     echo -e "qemu-i386 $PREFIX/share/quickbms/quickbms_4gb_files -a "$i $keyr" etc/toolcom.bms $dmp/"$dat" $down/output/"$dat"" | bash
done

for i in {91..180}
  do
     echo -e "qemu-i386 $PREFIX/share/quickbms/quickbms_4gb_files -a "$i $keyr" etc/toolcom.bms $dmp/"$dat" $down/output/"$dat"" | bash
done

for i in {181..270}
  do
     echo -e "qemu-i386 $PREFIX/share/quickbms/quickbms_4gb_files -a "$i $keyr" etc/toolcom.bms $dmp/"$dat" $down/output/"$dat"" | bash
done

for i in {271..360}
  do
     echo -e "qemu-i386 $PREFIX/share/quickbms/quickbms_4gb_files -a "$i $keyr" etc/toolcom.bms $dmp/"$dat" $down/output/"$dat"" | bash
done

for i in {361..450}
  do
     echo -e "qemu-i386 $PREFIX/share/quickbms/quickbms_4gb_files -a "$i $keyr" etc/toolcom.bms $dmp/"$dat" $down/output/"$dat"" | bash
done

for i in {451..540}
  do
     echo -e "qemu-i386 $PREFIX/share/quickbms/quickbms_4gb_files -a "$i $keyr" etc/toolcom.bms $dmp/"$dat" $down/output/"$dat"" | bash
done

for i in {541..630}
  do
     echo -e "qemu-i386 $PREFIX/share/quickbms/quickbms_4gb_files -a "$i $keyr" etc/toolcom.bms $dmp/"$dat" $down/output/"$dat"" | bash
done

for i in {631..720}
  do
     echo -e "qemu-i386 $PREFIX/share/quickbms/quickbms_4gb_files -a "$i $keyr" etc/toolcom.bms $dmp/"$dat" $down/output/"$dat"" | bash
done


for i in {721..810}
  do
     echo -e "qemu-i386 $PREFIX/share/quickbms/quickbms_4gb_files -a "$i $keyr" etc/toolcom.bms $dmp/"$dat" $down/output/"$dat"" | bash
done

echo "721..810 DONE"


for i in {811..900}
  do
     echo -e "qemu-i386 $PREFIX/share/quickbms/quickbms_4gb_files -a "$i $keyr" etc/toolcom.bms $dmp/"$dat" $down/output/"$dat"" | bash
done

for i in {901..990}
  do
     echo -e "qemu-i386 $PREFIX/share/quickbms/quickbms_4gb_files -a "$i $keyr" etc/toolcom.bms $dmp/"$dat" $down/output/"$dat"" | bash
done

for i in {991..1000}
  do
     echo -e "qemu-i386 $PREFIX/share/quickbms/quickbms_4gb_files -a "$i $keyr" etc/toolcom.bms $dmp/"$dat" $down/output/"$dat"" | bash
done


}












function pilkeystr {
    read -p "Please input decimpressed file: " keyr
    echo "are you sure the key is $keyr"
    read -p "Y OR N : " pil
       if [ $pil == Y ];
          then
              echo " OK THEN"
              i90
       elif [ $pil == y ];
          then 
              echo " OK THEN"
              i90
       else
            exit
     fi
}











#HEAD PROGRAM
echo "option 1 adalah option untuk tidak menggunakan decompressed offset"
echo "option 1 adalah option untuk menggunakan decompressed offset"

PS3='Please enter your choice: '
options=("option 1" "option 2" "Quit")
select dadi in "${options[@]}"
do
    case $dadi in
        "option 1")
            filedatfinder
            dirdatfolder
            i90
            ;;
        "Quit")
            exit
            
            ;;
        "option 2")
            filedatfinder
            dirdatfolder
            pilkeystr
            
            ;;
        *) echo "invalid option $REPLY";;
    esac
done 


